enum BoundNodeKind {
  literalExpression,
  binaryExpression,
  unaryExpression,
  emptyExpression,
  assignmentStatement,
  variableExpression,
  forLoop,
  block,
  printStatement,
  ifStatement,
  functionCallExpression,
  returnStatement,
  continueStatement,
  breakStatement,
}
